changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputFileEncoding=UTF-8
# Reference
referenceUrl=hibernate:spring:fr.avenirsesr.portfolio.activity.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.association.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.notification.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.backoffice.configuration.shared.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.student.progress.imported.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.student.progress.declared.activity.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.student.progress.declared.program.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.student.progress.declared.experience.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.student.progress.declared.skill.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.shared.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.trace.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.program.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.declaredskill.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.selfknowledge.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.file.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.interoperability.additionalskill.rome.infrastructure.adapter.model,\
fr.avenirsesr.portfolio.user.infrastructure.adapter.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
# DB
url=jdbc:postgresql://localhost:65432/avenirs_api
username=avenirs_api_admin
password=ENC(nrhrW8giUqCjQzWRBDVj/XYVStp8Tgxs)
driver=org.postgresql.Driver
defaultSchemaName=dev
log-level=debug
# Spring batch tables are not managed by liquibase
excludeObjects=table:batch_.*,sequence:batch_.*