databaseChangeLog:
  - changeSet:
      id: 011-1
      author: mouhameddiallo
      changes:
        - createTable:
            tableName: configuration
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: "value"
                  type: VARCHAR(255)
                  constraints:
                    nullable: false

              - column:
                  name: created_at
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false

              - column:
                  name: updated_at
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
        - sql:
            dbms: 'postgresql'
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE configuration OWNER TO ${avenirs.admin.role}
            stripComments: true
  - changeSet:
      id: 011-2
      author: mouhameddiallo
      changes:
        - insert:
            tableName: configuration
            columns:
              - column:
                  name: id
                  valueComputed: 'gen_random_uuid()'
              - column:
                  name: name
                  value: 'TRACE_MAX_DAY_REMAINING_NORMAL'
              - column:
                  name: "value"
                  value: '90'
        - insert:
            tableName: configuration
            columns:
              - column:
                  name: id
                  valueComputed: 'gen_random_uuid()'
              - column:
                  name: name
                  value: 'TRACE_MAX_DAY_REMAINING_WARNING'
              - column:
                  name: "value"
                  value: '30'
        - insert:
            tableName: configuration
            columns:
              - column:
                  name: id
                  valueComputed: 'gen_random_uuid()'
              - column:
                  name: name
                  value: 'TRACE_MAX_DAY_REMAINING_CRITICAL'
              - column:
                  name: "value"
                  value: '5'
        - sql:
            dbms: 'postgresql'
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE configuration OWNER TO ${avenirs.admin.role}
            stripComments: true

  - changeSet:
      id: create-updated-at-trigger-configuration
      author: bilelbanelhaq
      changes:
        - sql:
            sql: |
              DROP TRIGGER IF EXISTS trigger_set_updated_at_configuration ON "configuration";
              CREATE TRIGGER trigger_set_updated_at_configuration
              BEFORE UPDATE ON "configuration"
              FOR EACH ROW
              EXECUTE FUNCTION set_updated_at();
