databaseChangeLog:
  - changeSet:
      id: 011-1
      author: mouhameddiallo
      changes:
        - createTable:
            tableName: configuration
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: "value"
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
        - sql:
            dbms: 'postgresql'
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE configuration OWNER TO ${avenirs.admin.role}
            stripComments: true
  - changeSet:
      id: 011-2
      author: mouhameddiallo
      changes:
        - insert:
            tableName: configuration
            columns:
              - column:
                  name: id
                  valueComputed: 'gen_random_uuid()'
              - column:
                  name: name
                  value: 'TRACE_MAX_DAY_REMAINING_NORMAL'
              - column:
                  name: "value"
                  value: '90'
        - insert:
            tableName: configuration
            columns:
              - column:
                  name: id
                  valueComputed: 'gen_random_uuid()'
              - column:
                  name: name
                  value: 'TRACE_MAX_DAY_REMAINING_WARNING'
              - column:
                  name: "value"
                  value: '30'
        - insert:
            tableName: configuration
            columns:
              - column:
                  name: id
                  valueComputed: 'gen_random_uuid()'
              - column:
                  name: name
                  value: 'TRACE_MAX_DAY_REMAINING_CRITICAL'
              - column:
                  name: "value"
                  value: '5'
        - sql:
            dbms: 'postgresql'
            endDelimiter: \nGO
            splitStatements: true
            sql: ALTER TABLE configuration OWNER TO ${avenirs.admin.role}
            stripComments: true