name: Deploy on dev server
on:
  push:
    branches: [ develop, feat/518-deploy-workflow ]

jobs:
  call-main-ci:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/deploy-workflow.yaml@feat/518-deploy-workflow
    with:
      target_env: dev
      tag_name: "test"
    secrets: inherit
