name: Deploy on dev server
on:
  push:
    branches: [ develop ]

jobs:
  call-main-ci:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/deploy-workflow.yaml@main
    with:
      target_env: dev
    secrets: inherit
