name: Main Workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  call-main-ci:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/common-backend-workflow.yaml@main
    with:
      run_integration_tests: false

  call-check-imports:
    uses: ./.github/workflows/check-domain-layer-imports.yaml